ETL PROCESS

A) Extract

Read data

In [125]:
import pandas as pd

data = pd.read_csv('../data/DataForAssessment.csv')
data

,PacName,RegionName,FieldName,WellName,WellType,RigName,RigType,WaterDepth,Year,ReportType,...,WellStartDateTime,WellEndDateTime,FinalCost,FinalDays,WellNptPercentageWow,WellNptPercentage,CompletionCostPlan,CompletionCostActual,DrillingPlanWcpf,DrillingActualWcpf
0,PCSB,PM,ANGSI,ANGSI-E16,APPRAISAL CUM DEV/DEVELOPMENT,NAGA-5,JACK UP,69.000000,2019,NOOP,...,2019-02-09 13:00:00.000 +0000,2019-02-28 03:00:00.000 +0000,6283904.03,18.580000,0.000000,0.000000,NaN,NaN,NaN,NaN
1,PCSB,PM,ANGSI,ANGSI-E16,APPRAISAL CUM DEV/DEVELOPMENT,NAGA-5,JACK UP,69.000000,2019,FWR,...,2019-02-09 13:00:00.000 +0000,2019-02-28 03:00:00.000 +0000,6283904.03,18.580000,0.000000,0.000000,NaN,NaN,NaN,NaN
2,PCSB,PM,ANGSI,ANGSI-E16,APPRAISAL CUM DEV/DEVELOPMENT,NAGA-5,JACK UP,69.000000,2019,NOOP,...,2019-02-09 13:00:00.000 +0000,2019-02-28 03:00:00.000 +0000,6283904.03,18.580000,0.000000,0.000000,NaN,NaN,NaN,NaN
3,PCSB,PM,ANGSI,ANGSI-E16,APPRAISAL CUM DEV/DEVELOPMENT,NAGA-5,JACK UP,69.000000,2019,FWR,...,2019-02-09 13:00:00.000 +0000,2019-02-28 03:00:00.000 +0000,6283904.03,18.580000,0.000000,0.000000,NaN,NaN,NaN,NaN
4,PCSB,PM,ANGSI,ANGSI-E14,APPRAISAL CUM DEV/DEVELOPMENT,NAGA-5,JACK UP,69.000000,2019,NOOP,...,2018-12-14 11:30:00.000 +0000,2019-01-05 05:00:00.000 +0000,6513802.82,21.730000,11.560000,3.310000,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
133,PCSB,SK,WEST LUTONG A DEV,WEST LUTONG-A08ST3,APPRAISAL CUM DEV/DEVELOPMENT,T-10,PLATFORM TENDER-ASSISTED BARGE TYPE,30.480000,2020,FWR,...,2020-01-30 05:45:00.000 +0800,2020-06-24 18:30:00.000 +0800,14559861.47,70.468750,8.001177,7.538803,NaN,NaN,NaN,NaN
134,PTTEP,PM,WPPB INFILL DEV,WPPB-15/15ST1,APPRAISAL CUM DEV/DEVELOPMENT,GUNNLOD,JACK UP,40.200072,2022,NOOP,...,2022-06-17 08:00:00.000 +0800,2022-10-10 08:00:00.000 +0800,16026063.62,37.208332,1.259798,1.259798,NaN,NaN,NaN,NaN
135,PTTEP,PM,WPPB INFILL DEV,WPPB-15/15ST1,APPRAISAL CUM DEV/DEVELOPMENT,GUNNLOD,JACK UP,40.200072,2022,FWR,...,2022-06-17 08:00:00.000 +0800,2022-10-10 08:00:00.000 +0800,16026063.62,37.208332,1.259798,1.259798,NaN,NaN,NaN,NaN
136,PTTEP,PM,WPPB INFILL DEV,WPPB-14,APPRAISAL CUM DEV/DEVELOPMENT,GUNNLOD,JACK UP,40.200072,2022,NOOP,...,2022-06-21 18:00:00.000 +0800,2022-10-31 08:00:00.000 +0800,9160500.84,24.291666,34.905660,34.905660,NaN,NaN,NaN,NaN
137,PTTEP,PM,WPPB INFILL DEV,WPPB-14,APPRAISAL CUM DEV/DEVELOPMENT,GUNNLOD,JACK UP,40.200072,2022,FWR,...,2022-06-21 18:00:00.000 +0800,2022-10-31 08:00:00.000 +0800,9160500.84,24.291666,34.905660,34.905660,NaN,NaN,NaN,NaN

Check data type for each attributes

In [126]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 138 entries, 0 to 137
Data columns (total 27 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   PacName               138 non-null    object
 1   RegionName            136 non-null    object
 2   FieldName             138 non-null    object
 3   WellName              138 non-null    object
 4   WellType              138 non-null    object
 5   RigName               138 non-null    object
 6   RigType               136 non-null    object
 7   WaterDepth            138 non-null    float64
 8   Year                  138 non-null    int64
 9   ReportType            138 non-null    object
 10  DocumentName          4 non-null      object
 11  DocumentDate          83 non-null     object
 12  SubmittedAt           138 non-null    object
 13  SubmittedBy           138 non-null    object
 14  AfeCost               138 non-null    float64
 15  AfeDays               138 non-null    float64
 16  SpudDate              138 non-null    object
 17  WellStartDateTime     138 non-null    object
 18  WellEndDateTime       138 non-null    object
 19  FinalCost             138 non-null    float64
 20  FinalDays             138 non-null    float64
 21  WellNptPercentageWow  138 non-null    float64
 22  WellNptPercentage     138 non-null    float64
 23  CompletionCostPlan    0 non-null      float64
 24  CompletionCostActual  0 non-null      float64
 25  DrillingPlanWcpf      0 non-null      float64
 26  DrillingActualWcpf    0 non-null      float64
dtypes: float64(11), int64(1), object(15)
memory usage: 29.2+ KB

B) Transform

In [127]:
num_rows = data.shape[0]
num_cols = data.shape[1]

print(f"Rows: {num_rows}")
print(f"Columns: {num_cols}")

Rows: 138
Columns: 27

1. Standardize string value

In [128]:
import numpy as np

wellname_mapping = {
    'AAZ 1': 'AAZ-1',
    'BERGADING-C1 (A)': 'BERGADING-C1',
    'BUNGA KESUMBA A-4': 'BUNGA KESUMBA-A4',
    'LANG LEBAH - 2': 'LANG LEBAH-2',
    'TABU-B19 ST1': 'TABU-B19ST1',
    'TABU-B11 ST1': 'TABU-B11ST1',
    'TABU-B23 ST1': 'TABU-B23ST1',
    'KCP-1': 'KECAPI-1'
}

data['WellName'] = data['WellName'].replace(wellname_mapping)

Split the combine well name

In [129]:
mask = data['WellName'] == 'WPPB-15/15ST1'

data.loc[mask, 'WellName'] = 'WPPB-15'

duplicated_rows = data.loc[mask].copy()
duplicated_rows['WellName'] = 'WPPB-15ST1'

data = pd.concat([data, duplicated_rows], ignore_index=True)

In [130]:
print(data['WellName'].unique())

['ANGSI-E16' 'ANGSI-E14' 'ANGSI-E15' 'AJK-A1ST1' 'AJK-A2ST1' 'AJK-A2'
 'AJK-A1' 'BESA-03' 'BESA-11' 'BESA-12' 'BESA-02' 'BENTARA-A2'
 'BENTARA-A3' 'BENTARA-A4' 'BENTARA-A1' 'BERGADING-C1' 'BU-3' 'BU-1'
 'BU-2' 'BESAR-A4' 'AAZ-1' 'BUNGA KESUMBA-A4' 'GAGAU-1' 'TEST-SHELL'
 'GK-W721C' 'GRK-101' 'J4-A09' 'J4-A02ST1' 'J4-A06ST1' 'KAMOMIL-1'
 'KECAPI-1' 'KERDAS-1' 'KNDW-D15' 'KNDW-D10' 'LANG LEBAH-2' 'LARUT-A26'
 'LAYANG-2' 'M1-A111' 'MACHINCANG-1' 'PRPA-13' 'SALAM-3' 'SEPAT-10'
 'SNPA-24' 'SNPA-23' 'SNPA-14' 'SNPA-12' 'SNPA-11' 'SASA-02' 'SAPA-17ST1'
 'SAPA-01ST2' 'SAPA-03' 'SASA-19' 'SJ-609A' 'SJ-609B' 'TABU-B19ST1'
 'TABU-B11ST1' 'TABU-B23ST1' 'TABU-B08ST2' 'TABU-A11ST1'
 'WEST LUTONG-A13ST2' 'WEST LUTONG-A08ST3' 'WPPB-15' 'WPPB-14'
 'WPPB-15ST1']

In [131]:
#Check total rows and columns
num_rows = data.shape[0]
num_cols = data.shape[1]

print(f"Rows: {num_rows}")
print(f"Columns: {num_cols}")

Rows: 140
Columns: 27

In [132]:
import re

def clean_fieldname(x):
    if pd.isna(x):
        return x

    x = x.upper().strip()

    # Remove known suffix noise
    x = re.sub(r'\b(DEV|EXP|EXPL|DEPS)\b.*$', '', x).strip()

    # Remove patterns like -A4, -1, A-111
    x = re.sub(r'[-][A-Z]?\d+$', '', x).strip()

    # Remove trailing single letters
    x = re.sub(r'\s+[A-Z]$', '', x).strip()

    # Standardize field names
    field_mapping = {
        'KCP': 'KECAPI',
        'KECAPI': 'KECAPI',
        'GAMUSUT KAKAP': 'GUMUSUT-KAKAP'
    }

    x = field_mapping.get(x, x)

    # Clean double spaces
    x = re.sub(r'\s+', ' ', x)

    return x

data['FieldName'] = data['FieldName'].apply(clean_fieldname)

In [133]:
print(data['FieldName'].unique())

['ANGSI' 'ANJUNG KECIL' 'BELUM' 'BENTARA' 'BERGADING' 'BERYL' 'BESAR'
 'BULOH' 'BUNGA KESUMBA' 'GAGAU' 'GUMUSUT-KAKAP' 'GOREK' 'J4' 'KAMOMIL'
 'KECAPI' 'KERDAS' 'KINABALU' 'LANG LEBAH' 'LARUT' 'LAYANG' 'M1'
 'MACHINCANG' 'PRPA' 'SALAM' 'SEPAT' 'SERENDAH' 'SOUTH ACIS' 'ST JOSEPH'
 'TABU' 'WEST LUTONG' 'WPPB INFILL']

Fill in null value in RegionName

In [134]:
data.loc[
    (data['FieldName'] == 'BULOH') & (data['RegionName'].isna()),
    'RegionName'
] = 'SB'   # replace with the correct region

In [135]:
print(data['RegionName'].unique())

['PM' 'SK' 'SB']

In [ ]:
data

In [136]:
#Standardize same meaning with different words (missing special character, wrong spelling)
data['RigName'] = data['RigName'].str.strip()
data['RigName'] = data['RigName'].replace('NAGA - 5', 'NAGA-5')
data['RigName'] = data['RigName'].replace('NAGA 4', 'NAGA-4')
data['RigName'] = data['RigName'].replace('NAGA 7', 'NAGA-7')

data['RigType'] = data['RigType'].str.strip()
data['RigType'] = data['RigType'].replace('JACK UP', 'JACK-UP')
data['RigType'] = data['RigType'].replace('SEMI-SUB', 'SEMI-SUBMERSIBLE')
#data['RigType'] = data['RigType'].replace('Semi-Submersible', 'SEMI-SUBMERSIBLE')
data['RigType'] = data['RigType'].str.upper()

data['SubmittedBy'] = data['SubmittedBy'].str.strip()
data.loc[~data['SubmittedBy'].isin(['system', 'aem']), 'SubmittedBy'] = np.nan

In [137]:
print(data['RigName'].unique())

['NAGA-5' 'MIST' 'AQUA MARINE DRILLER' 'ENSCO-52' 'NAGA-2' 'RIGLESS' 'T-9'
 'NAGA-4' 'SAPURA ALLIANCE' 'BORR SAGA' 'PERISAI PACIFIC 101'
 'WEST CARINA' 'MAERSK VIKING' 'NAGA-7' 'DEEPWATER NAUTILUS' 'NAGA-3'
 'PVD III' 'SAGA' 'SAPURA BERANI' 'GALVESTON KEY' 'HAKURYU-5' 'GUNNLOD'
 'ABAN VIII' 'BORR GUNNLOD' 'PV DRILLING' 'T-10']

In [138]:
print(data['RigType'].unique())

['JACK-UP' 'RIGLESS' 'TENDER ASSISTED DRILLING RIG (TADR)'
 'SEMI-SUBMERSIBLE' 'DRILL SHIP' nan 'SUPER B CLASS'
 'PLATFORM TENDER-ASSISTED SEMI-SUB TYPE VESSEL'
 'PLATFORM TENDER-ASSISTED BARGE TYPE']

In [139]:
print(data['SubmittedBy'].unique())

['system' 'aem' nan]

2. Standardize decimal values

In [140]:
#Convert to numeric datatype
data['WaterDepth'] = pd.to_numeric(data['WaterDepth'], errors='coerce')
data['AfeCost'] = pd.to_numeric(data['AfeCost'], errors='coerce')
data['AfeDays'] = pd.to_numeric(data['AfeDays'], errors='coerce')
data['FinalCost'] = pd.to_numeric(data['FinalCost'], errors='coerce')
data['FinalDays'] = pd.to_numeric(data['FinalDays'], errors='coerce')
data['WellNptPercentageWow'] = pd.to_numeric(data['WellNptPercentageWow'], errors='coerce')
data['WellNptPercentage'] = pd.to_numeric(data['WellNptPercentage'], errors='coerce')
data['CompletionCostPlan'] = pd.to_numeric(data['CompletionCostPlan'], errors='coerce')
data['CompletionCostActual'] = pd.to_numeric(data['CompletionCostActual'], errors='coerce')
data['DrillingPlanWcpf'] = pd.to_numeric(data['DrillingPlanWcpf'], errors='coerce')
data['DrillingActualWcpf'] = pd.to_numeric(data['DrillingActualWcpf'], errors='coerce')

#round to fixed number of decimal places
data['WaterDepth'] = data['WaterDepth'].round(2)
data['AfeCost'] = data['AfeCost'].round(2)
data['AfeDays'] = data['AfeDays'].round(2)
data['FinalCost'] = data['FinalCost'].round(2)
data['FinalDays'] = data['FinalDays'].round(2)
data['WellNptPercentageWow'] = data['WellNptPercentageWow'].round(2)
data['WellNptPercentage'] = data['WellNptPercentage'].round(2)
data['CompletionCostPlan'] = data['CompletionCostPlan'].round(2)
data['CompletionCostActual'] = data['CompletionCostActual'].round(2)
data['DrillingPlanWcpf'] = data['DrillingPlanWcpf'].round(2)
data['DrillingActualWcpf'] = data['DrillingActualWcpf'].round(2)

3. Standardize datetime values

In [141]:
#Change to date only
date_cols = ['DocumentDate', 'SpudDate']

for col in date_cols:
    data[col] = pd.to_datetime(data[col], errors='coerce', utc=True)
    data[col] = data[col].dt.strftime('%Y-%m-%d')

In [142]:
#Change to proper formate datetime
datetime_cols = ['SubmittedAt', 'WellStartDateTime', 'WellEndDateTime']

for col in datetime_cols:
    data[col] = (
        pd.to_datetime(data[col], errors='coerce', utc=True)
          .dt.strftime('%Y-%m-%d %H:%M:%S')
    )

In [143]:
data

,PacName,RegionName,FieldName,WellName,WellType,RigName,RigType,WaterDepth,Year,ReportType,...,WellStartDateTime,WellEndDateTime,FinalCost,FinalDays,WellNptPercentageWow,WellNptPercentage,CompletionCostPlan,CompletionCostActual,DrillingPlanWcpf,DrillingActualWcpf
0,PCSB,PM,ANGSI,ANGSI-E16,APPRAISAL CUM DEV/DEVELOPMENT,NAGA-5,JACK-UP,69.0,2019,NOOP,...,2019-02-09 13:00:00,2019-02-28 03:00:00,6283904.03,18.58,0.00,0.00,NaN,NaN,NaN,NaN
1,PCSB,PM,ANGSI,ANGSI-E16,APPRAISAL CUM DEV/DEVELOPMENT,NAGA-5,JACK-UP,69.0,2019,FWR,...,2019-02-09 13:00:00,2019-02-28 03:00:00,6283904.03,18.58,0.00,0.00,NaN,NaN,NaN,NaN
2,PCSB,PM,ANGSI,ANGSI-E16,APPRAISAL CUM DEV/DEVELOPMENT,NAGA-5,JACK-UP,69.0,2019,NOOP,...,2019-02-09 13:00:00,2019-02-28 03:00:00,6283904.03,18.58,0.00,0.00,NaN,NaN,NaN,NaN
3,PCSB,PM,ANGSI,ANGSI-E16,APPRAISAL CUM DEV/DEVELOPMENT,NAGA-5,JACK-UP,69.0,2019,FWR,...,2019-02-09 13:00:00,2019-02-28 03:00:00,6283904.03,18.58,0.00,0.00,NaN,NaN,NaN,NaN
4,PCSB,PM,ANGSI,ANGSI-E14,APPRAISAL CUM DEV/DEVELOPMENT,NAGA-5,JACK-UP,69.0,2019,NOOP,...,2018-12-14 11:30:00,2019-01-05 05:00:00,6513802.82,21.73,11.56,3.31,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
135,PTTEP,PM,WPPB INFILL,WPPB-15,APPRAISAL CUM DEV/DEVELOPMENT,GUNNLOD,JACK-UP,40.2,2022,FWR,...,2022-06-17 00:00:00,2022-10-10 00:00:00,16026063.62,37.21,1.26,1.26,NaN,NaN,NaN,NaN
136,PTTEP,PM,WPPB INFILL,WPPB-14,APPRAISAL CUM DEV/DEVELOPMENT,GUNNLOD,JACK-UP,40.2,2022,NOOP,...,2022-06-21 10:00:00,2022-10-31 00:00:00,9160500.84,24.29,34.91,34.91,NaN,NaN,NaN,NaN
137,PTTEP,PM,WPPB INFILL,WPPB-14,APPRAISAL CUM DEV/DEVELOPMENT,GUNNLOD,JACK-UP,40.2,2022,FWR,...,2022-06-21 10:00:00,2022-10-31 00:00:00,9160500.84,24.29,34.91,34.91,NaN,NaN,NaN,NaN
138,PTTEP,PM,WPPB INFILL,WPPB-15ST1,APPRAISAL CUM DEV/DEVELOPMENT,GUNNLOD,JACK-UP,40.2,2022,NOOP,...,2022-06-17 00:00:00,2022-10-10 00:00:00,16026063.62,37.21,1.26,1.26,NaN,NaN,NaN,NaN
139,PTTEP,PM,WPPB INFILL,WPPB-15ST1,APPRAISAL CUM DEV/DEVELOPMENT,GUNNLOD,JACK-UP,40.2,2022,FWR,...,2022-06-17 00:00:00,2022-10-10 00:00:00,16026063.62,37.21,1.26,1.26,NaN,NaN,NaN,NaN

Split the data according to the database schema

REGIONS

In [144]:
regions = (
    data[['RegionName']]
    .drop_duplicates()
)

regions['RegionId'] = range(1, len(regions) + 1)

regions = regions[['RegionId', 'RegionName']]

regions

    RegionId RegionName
0          1         PM
10         2         SK
44         3         SB

FIELDS

In [145]:
fields = (
    data[['RegionName', 'FieldName']]
    .drop_duplicates()
)

fields = fields.merge(regions, on='RegionName', how='left')

fields['FieldId'] = range(1, len(fields) + 1)

fields = fields[['FieldId', 'RegionId', 'FieldName']]

fields

    FieldId  RegionId      FieldName
0         1         1          ANGSI
1         2         2   ANJUNG KECIL
2         3         2          BELUM
3         4         2        BENTARA
4         5         1      BERGADING
5         6         2          BERYL
6         7         1          BESAR
7         8         3          BULOH
8         9         3  BUNGA KESUMBA
9        10         2          GAGAU
10       11         1  GUMUSUT-KAKAP
11       12         2          GOREK
12       13         2             J4
13       14         2        KAMOMIL
14       15         2         KECAPI
15       16         2         KERDAS
16       17         3       KINABALU
17       18         2     LANG LEBAH
18       19         1          LARUT
19       20         2         LAYANG
20       21         2             M1
21       22         2     MACHINCANG
22       23         2           PRPA
23       24         2          SALAM
24       25         1          SEPAT
25       26         2       SERENDAH
26       27         2     SOUTH ACIS
27       28         3      ST JOSEPH
28       29         1           TABU
29       30         2    WEST LUTONG
30       31         1    WPPB INFILL

PAC

In [146]:
pac = (
    data[['PacName']]
    .drop_duplicates()
)

pac = pac[pac['PacName'].notna()]

pac['PacId'] = range(1, len(pac) + 1)

pac = pac[['PacId', 'PacName']]

pac

     PacId         PacName
0        1            PCSB
10       2         VESTIGO
18       3           PTTEP
34       4            HESS
36       5       JX NIPPON
44       6  TEST PAC2 EDIT
48       7             COP
50       8           SHELL
62       9         ROC OIL
76      10          REPSOL
84      11            NOEX
102     12          MURPHY
116     13    SEA HIBISCUS
120     14          EMEPMI

WELLS

In [147]:
wells = (
    data[['FieldName',
          'PacName',
          'WellName',
          'WellType',
          'WaterDepth',
          'Year']]
    .drop_duplicates()
)

wells = wells.merge(fields[['FieldId', 'FieldName']], on='FieldName', how='left')
wells = wells.merge(pac[['PacId', 'PacName']], on='PacName', how='left')

wells['WellId'] = range(1, len(wells) + 1)

wells = wells[['WellId', 'FieldId', 'PacId',
               'WellName', 'WellType', 'WaterDepth', 'Year']]

wells

,WellId,FieldId,PacId,WellName,WellType,WaterDepth,Year
0,1,1,1,ANGSI-E16,APPRAISAL CUM DEV/DEVELOPMENT,69.00,2019
1,2,1,1,ANGSI-E14,APPRAISAL CUM DEV/DEVELOPMENT,69.00,2019
2,3,1,1,ANGSI-E15,APPRAISAL CUM DEV/DEVELOPMENT,69.00,2019
3,4,2,2,AJK-A1ST1,APPRAISAL CUM DEV/DEVELOPMENT,70.50,2019
4,5,2,2,AJK-A2ST1,APPRAISAL CUM DEV/DEVELOPMENT,70.50,2019
...,...,...,...,...,...,...,...
60,61,30,1,WEST LUTONG-A13ST2,APPRAISAL CUM DEV/DEVELOPMENT,30.48,2020
61,62,30,1,WEST LUTONG-A08ST3,APPRAISAL CUM DEV/DEVELOPMENT,30.48,2020
62,63,31,3,WPPB-15,APPRAISAL CUM DEV/DEVELOPMENT,40.20,2022
63,64,31,3,WPPB-14,APPRAISAL CUM DEV/DEVELOPMENT,40.20,2022
64,65,31,3,WPPB-15ST1,APPRAISAL CUM DEV/DEVELOPMENT,40.20,2022

RIGS

In [148]:
rigs = (
    data[['RigName', 'RigType']]
    .drop_duplicates()
)

rigs['RigId'] = range(1, len(rigs) + 1)

rigs = rigs[['RigId', 'RigName', 'RigType']]

rigs

     RigId              RigName                                        RigType
0        1               NAGA-5                                        JACK-UP
10       2                 MIST                                        JACK-UP
16       3  AQUA MARINE DRILLER                                        JACK-UP
18       4             ENSCO-52                                        JACK-UP
32       5               NAGA-2                                        JACK-UP
34       6              RIGLESS                                        RIGLESS
36       7                  T-9            TENDER ASSISTED DRILLING RIG (TADR)
42       8               NAGA-4                                        JACK-UP
44       9      SAPURA ALLIANCE            TENDER ASSISTED DRILLING RIG (TADR)
46      10            BORR SAGA                                        JACK-UP
48      11  PERISAI PACIFIC 101                               SEMI-SUBMERSIBLE
50      12          WEST CARINA                                        JACK-UP
52      13        MAERSK VIKING                                     DRILL SHIP
60      14               NAGA-7                               SEMI-SUBMERSIBLE
68      15   DEEPWATER NAUTILUS                               SEMI-SUBMERSIBLE
70      16               NAGA-4                                            NaN
74      17               NAGA-3                                        JACK-UP
76      18              PVD III                                        JACK-UP
80      19                 SAGA                                  SUPER B CLASS
82      20        SAPURA BERANI  PLATFORM TENDER-ASSISTED SEMI-SUB TYPE VESSEL
84      21        SAPURA BERANI            TENDER ASSISTED DRILLING RIG (TADR)
86      22        GALVESTON KEY  PLATFORM TENDER-ASSISTED SEMI-SUB TYPE VESSEL
88      23            HAKURYU-5                               SEMI-SUBMERSIBLE
90      24              GUNNLOD                                        JACK-UP
94      25            ABAN VIII                                        JACK-UP
106     26         BORR GUNNLOD                                        JACK-UP
116     27          PV DRILLING                                        JACK-UP
130     28                 T-10            PLATFORM TENDER-ASSISTED BARGE TYPE

WELL_OPERATIONS

In [149]:
operations = (
    data[
        [
            'WellName',
            'RigName',
            'AfeCost',
            'AfeDays',
            'SpudDate',
            'WellStartDateTime',
            'WellEndDateTime',
            'FinalCost',
            'FinalDays',
            'WellNptPercentageWow',
            'WellNptPercentage',
            'CompletionCostPlan',
            'CompletionCostActual',
            'DrillingPlanWcpf',
            'DrillingActualWcpf'
        ]
    ]
    .drop_duplicates()
)

operations = operations.merge(
    wells[['WellId', 'WellName']],
    on='WellName',
    how='left'
)

operations = operations.merge(
    rigs[['RigId', 'RigName']],
    on='RigName',
    how='left'
)

operations['OperationId'] = range(1, len(operations) + 1)

operations = operations[
    [
        'OperationId',
        'WellId',
        'RigId',
        'AfeCost',
        'AfeDays',
        'SpudDate',
        'WellStartDateTime',
        'WellEndDateTime',
        'FinalCost',
        'FinalDays',
        'WellNptPercentageWow',
        'WellNptPercentage',
        'CompletionCostPlan',
        'CompletionCostActual',
        'DrillingPlanWcpf',
        'DrillingActualWcpf'
    ]
]

operations

,OperationId,WellId,RigId,AfeCost,AfeDays,SpudDate,WellStartDateTime,WellEndDateTime,FinalCost,FinalDays,WellNptPercentageWow,WellNptPercentage,CompletionCostPlan,CompletionCostActual,DrillingPlanWcpf,DrillingActualWcpf
0,1,1,1,8473824.90,24.10,2019-02-10,2019-02-09 13:00:00,2019-02-28 03:00:00,6283904.03,18.58,0.00,0.00,NaN,NaN,NaN,NaN
1,2,2,1,7880044.34,23.10,2018-12-15,2018-12-14 11:30:00,2019-01-05 05:00:00,6513802.82,21.73,11.56,3.31,NaN,NaN,NaN,NaN
2,3,3,1,8993906.20,27.00,2018-11-12,2018-11-12 00:00:00,2019-01-24 20:00:00,7583625.47,24.48,1.48,1.29,NaN,NaN,NaN,NaN
3,4,4,2,8373993.00,22.20,2019-06-29,2019-06-19 00:00:00,2019-08-23 22:30:00,8990865.00,29.45,24.08,24.08,NaN,NaN,NaN,NaN
4,5,5,2,8100000.00,20.50,2019-07-12,2019-05-30 18:00:00,2019-08-31 00:30:00,6081416.00,21.14,6.60,6.60,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
67,68,61,28,9926255.83,34.07,2020-02-20,2020-02-14 15:30:00,2020-05-14 18:00:00,8624696.89,37.77,13.70,12.93,NaN,NaN,NaN,NaN
68,69,62,28,13892863.88,62.84,2020-02-09,2020-01-29 21:45:00,2020-06-24 10:30:00,14559861.47,70.47,8.00,7.54,NaN,NaN,NaN,NaN
69,70,63,24,7999172.03,17.44,2022-06-17,2022-06-17 00:00:00,2022-10-10 00:00:00,16026063.62,37.21,1.26,1.26,NaN,NaN,NaN,NaN
70,71,64,24,5866029.56,8.48,2022-06-22,2022-06-21 10:00:00,2022-10-31 00:00:00,9160500.84,24.29,34.91,34.91,NaN,NaN,NaN,NaN
71,72,65,24,7999172.03,17.44,2022-06-17,2022-06-17 00:00:00,2022-10-10 00:00:00,16026063.62,37.21,1.26,1.26,NaN,NaN,NaN,NaN

REPORTS

In [150]:
reports = (
    data[['WellName',
          'RigName',
          'ReportType',
          'DocumentName',
          'DocumentDate',
          'SubmittedAt',
          'SubmittedBy']]
    .drop_duplicates()
)

reports = reports.merge(
    wells[['WellId', 'WellName']],
    on='WellName',
    how='left'
)

reports = reports.merge(
    rigs[['RigId', 'RigName']],
    on='RigName',
    how='left'
)

reports = reports.merge(
    operations[['OperationId', 'WellId', 'RigId']],
    on=['WellId', 'RigId'],
    how='left'
)

reports['ReportId'] = range(1, len(reports) + 1)

reports = reports[
    ['ReportId',
     'OperationId',
     'ReportType',
     'DocumentName',
     'DocumentDate',
     'SubmittedAt',
     'SubmittedBy']
]

reports

,ReportId,OperationId,ReportType,DocumentName,DocumentDate,SubmittedAt,SubmittedBy
0,1,1,NOOP,NaN,2019-02-04,2025-05-09 07:33:30,system
1,2,1,FWR,NaN,2019-03-15,2025-05-09 07:33:30,system
2,3,2,NOOP,NaN,2018-10-15,2025-05-22 18:49:28,system
3,4,2,FWR,NaN,2019-02-16,2025-05-22 18:49:28,system
4,5,3,NOOP,NaN,2018-08-15,2025-05-09 07:33:30,system
...,...,...,...,...,...,...,...
143,144,70,FWR,NaN,NaN,2024-12-14 03:18:18,aem
144,145,71,NOOP,NaN,NaN,2024-12-14 03:18:18,aem
145,146,71,FWR,NaN,NaN,2024-12-14 03:18:18,aem
146,147,72,NOOP,NaN,NaN,2024-12-14 03:18:18,aem
147,148,72,FWR,NaN,NaN,2024-12-14 03:18:18,aem

C) Load

Connect the database

In [151]:
import sqlite3

conn = sqlite3.connect("drilling_operations.db")

Load the data according to the hierarchy

In [152]:
# Parent tables first
regions.to_sql("REGIONS", conn, if_exists="append", index=False)
pac.to_sql("PAC", conn, if_exists="append", index=False)

14

In [153]:
# Dependent tables
fields.to_sql("FIELDS", conn, if_exists="append", index=False)
wells.to_sql("WELLS", conn, if_exists="append", index=False)
rigs.to_sql("RIGS", conn, if_exists="append", index=False)

28

In [154]:
# Fact tables
operations.to_sql("WELL_OPERATIONS", conn, if_exists="append", index=False)
reports.to_sql("REPORTS", conn, if_exists="append", index=False)

148

Close the connection

In [155]:
conn.commit()
conn.close()